package org.javaculator.antlr4.exceptions.impl;

import org.javaculator.antlr4.exceptions.JavaculatorException;

/**
 * Exception thrown when an identifier provided by the user is either missing or null.
 * <p>
 * This exception extends {@link RuntimeException} and signals that an operation
 * failed because an invalid or non-existent identifier was encountered.
 * </p>
 */
public class MissingOrNullIdentifierException extends JavaculatorException {

    /**
     * Constructs a new {@link  MissingOrNullIdentifierException} with a detailed message.
     * <p>
     * The exception message is generated by formatting the provided identifier into a
     * predefined message template.
     * </p>
     *
     * @param identifier the identifier that is missing or null
     */
    public MissingOrNullIdentifierException(String identifier) {
        super("User passed identifier=\"%s\" that is missing or null:".formatted(identifier));
    }
}
