package org.javaculator.antlr4.exceptions.impl;

import org.javaculator.antlr4.exceptions.JavaculatorException;

/**
 * Exception thrown when an unknown operator is encountered during a calculation.
 * <p>
 * This exception extends {@link RuntimeException} and is used to indicate that an operator
 * provided by the user is not recognized or supported by the calculator.
 * </p>
 */
public class UnknownOperatorException extends JavaculatorException {

    /**
     * Constructs a new {@link  UnknownOperatorException} with a detailed message.
     * <p>
     * The exception message is generated by formatting the provided operator into a predefined
     * message template.
     * </p>
     *
     * @param operator the operator that is unknown or unsupported.
     */
    public UnknownOperatorException(String operator) {
        super("User passed an unknown operator op=\"%s\" to calculator:".formatted(operator));
    }
}
